import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import worker from '../src/worker.mjs';
import {page} from '../src/page.mjs';
import {readFileSync} from 'node:fs';

// This does not simulate or manufacture an authenticated platform identity.
// Positive session authentication is a hosting integration test, not this unit test.
test('browser and MCP data endpoints reject requests without platform identity',async()=>{
  for(const path of ['/api/market','/mcp']){
    const body=path==='/mcp'?{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'get_intraday',arguments:{symbol:'600522'}}}:{name:'get_intraday',arguments:{symbol:'600522'}};
    const response=await worker.fetch(new Request('https://site.test'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}));
    assert.equal(response.status,401);
    assert.match(response.headers.get('content-type'),/application\/json/);
  }
});
function browser(fetch,local=false){
  const ctx=new Proxy({},{get:()=>()=>{}}),els={};
  function element(id){return els[id]??=( {value:id==='symbol'?'600522':id==='adjustment'?'none':'',hidden:true,clientWidth:800,innerHTML:'',textContent:'',className:'',addEventListener(name,fn){this[name]=fn},getContext(){return ctx},querySelectorAll(){return []},setAttribute(){},getBoundingClientRect(){return {left:0}}});}
  const sandbox={document:{getElementById:element},window:{addEventListener(){},devicePixelRatio:1},fetch,setTimeout,clearTimeout,performance:{now:()=>0},console};
  for(const m of page.matchAll(/id="([^"]+)"/g))element(m[1]);
  vm.runInNewContext(page.match(/<script>([\s\S]*)<\/script>/)[1].replace('const PAGE_PUBLIC_RETENTION_ALLOWED=false;','const PAGE_PUBLIC_RETENTION_ALLOWED='+local+';'),sandbox);
  return {els,sandbox,ready:()=>new Promise(r=>setTimeout(r,20)),submit:()=>els.form.submit({preventDefault(){}}),eval:s=>vm.runInNewContext(s,sandbox)};
}
function localBrowser(fetch){return browser(fetch,true);}
const stamp='2026-09-30T14:01:00+08:00';
const common={source:'tencent',source_timestamp:stamp,fetched_at:'2026-09-30T06:02:00Z',freshness:{status:'recent',age_seconds:60},warnings:[]};
const samples={get_quotes:{quotes:[{...common,symbol:'sh600522',name:'中天科技',price:31,previous_close:30,open:30.2,high:32,low:30,volume_shares:10000,amount_cny:310000,book:{asks:Array.from({length:5},()=>({price:31.1,volume_shares:200})),bids:Array.from({length:5},()=>({price:30.9,volume_shares:300}))}}]},get_intraday:{...common,points:[{source_timestamp:stamp,price:31,cumulative_volume_shares:10000,cumulative_amount_cny:null,average_price_cny:null,interval_volume_shares:null,interval_minutes:null}]},get_macd:{...common,parameters:{warmup_bars:120,warmup_target:250,seed_sensitive:true},points:[{source_timestamp:stamp,dif:1,dea:.5,macd_histogram:1}]},get_auction:{...common,source:'eastmoney',points:[]},get_bars:{...common,adjustment:'none',bars:Array.from({length:140},(_,i)=>({source_timestamp:stamp,open:i+1,high:i+3,low:i,close:i+2,volume_shares:100,amount_cny:null}))}};
function response(data){return new Response(JSON.stringify({data}),{headers:{'content-type':'application/json'}})}
test('workspace retrieves all four independent panels through session-authenticated browser API',async()=>{
 let names=[];const ui=browser(async(url,options)=>{assert.equal(url,'/api/market');assert.equal(options.credentials,'same-origin');assert.equal(options.redirect,'manual');assert.equal(options.headers.authorization,undefined);const b=JSON.parse(options.body);names.push(b.name);return response(samples[b.name]);});await ui.ready();assert.deepEqual(names.sort(),['get_auction','get_intraday','get_macd','get_quotes']);assert.match(ui.els['quote-body'].innerHTML,/中天科技/);assert.match(ui.els.book.innerHTML,/卖 5/);assert.match(ui.els['chart-readout'].textContent,/均价 —/);assert.match(ui.els['chart-readout'].textContent,/14:01:00/);assert.match(ui.els['quote-status'].textContent,/14:02:00/);assert.equal(ui.els.load.disabled,false);
});
test('null remains absent and MA uses requested warmup before display slicing',async()=>{const ui=browser(async(_u,o)=>response(samples[JSON.parse(o.body).name]));await ui.ready();assert.equal(ui.eval('fmt(null)'),'—');assert.equal(ui.eval('mean([{close:null},{close:2}],1,2)'),null);assert.equal(ui.eval('mean([{close:1},{close:2}],1,2)'),1.5);ui.eval("mode='1d'");await ui.eval('loadCharts()');assert.equal(ui.eval('charts.chart.rows.length'),120);assert.equal(ui.eval('charts.chart.rows[0].ma20'),12.5);assert.match(ui.els['chart-readout'].textContent,/额 — 元/);});
test('single panel failure preserves quote and other panels',async()=>{const ui=browser(async(_u,o)=>{const b=JSON.parse(o.body);return b.name==='get_auction'?new Response(JSON.stringify({error:{message:'UPSTREAM_TIMEOUT'}}),{status:502,headers:{'content-type':'application/json'}}):response(samples[b.name]);});await ui.ready();assert.match(ui.els['quote-body'].innerHTML,/中天科技/);assert.match(ui.els['auction-status'].textContent,/超时/);assert.match(ui.els.status.textContent,/1 个面板/);});
test('plain text unauthorized never leaks parsing errors and offers sign in',async()=>{const ui=browser(async()=>new Response('Unauthorized',{status:401,headers:{'content-type':'text/plain'}}));await ui.ready();assert.match(ui.els['chart-status'].textContent,/登录/);assert.doesNotMatch(ui.els.status.textContent,/Unexpected token/);assert.equal(ui.els.signin.hidden,false);assert.equal(ui.els.load.disabled,false);assert.match(page,/href="\/signin-with-chatgpt\?return_to=%2F" target="_top"/);});
test('403 HTML invalid JSON and upstream errors fail independently without exceptions',async()=>{for(const make of [()=>new Response('Forbidden',{status:403}),()=>new Response('<html>Sign in</html>',{headers:{'content-type':'text/html'}}),()=>new Response('bad',{headers:{'content-type':'application/json'}})]){const ui=browser(async()=>make());await ui.ready();assert.match(ui.els.status.textContent,/4 个面板/);assert.equal(ui.els.load.disabled,false);}});
test('intraday cross-session interval is distinguished in precise readout',async()=>{const d={...samples.get_intraday,points:[{...samples.get_intraday.points[0],interval_minutes:91,interval_volume_shares:30000}]};const ui=browser(async(_u,o)=>{const b=JSON.parse(o.body);return response(b.name==='get_intraday'?d:samples[b.name]);});await ui.ready();assert.match(ui.els['chart-readout'].textContent,/91 分钟区间量（灰色）/);});

test('late prior-cycle response cannot overwrite newly selected timeframe',async()=>{let release;const pending=new Promise(r=>release=r);let calls=0;const ui=browser(async(_u,o)=>{const b=JSON.parse(o.body);if(b.name==='get_bars'&&++calls===1){await pending;return response({...samples.get_bars,source:'old'});}return response(samples[b.name]);});await ui.ready();ui.eval("mode='1d'");const old=ui.eval('loadCharts()');ui.eval("mode='1w'");await ui.eval('loadCharts()');release();await old;assert.equal(ui.eval('state.chart.source'),'tencent');assert.match(ui.els['chart-title'].textContent,/周 K/);});
test('known warnings are rendered in Chinese and unknown warnings remain inspectable',async()=>{const ui=browser(async(_u,o)=>response(samples[JSON.parse(o.body).name]));await ui.ready();assert.equal(ui.eval("warningText('ALTERNATE_HISTORY_SOURCE_FAILED; see candidates')"),'另一路来源失败，本次使用可用来源');assert.match(ui.eval("warningText('NEW_PROVIDER_CAVEAT')"),/NEW_PROVIDER_CAVEAT/);});

test('mobile navigation exposes week month and auction before quote and chart panels',()=>{
 assert.ok(page.indexOf('id="periods"')<page.indexOf('class="card overview"'));
 assert.match(page,/data-mode="1w"[^>]*>周K/);assert.match(page,/data-mode="1mo"[^>]*>月K/);
 assert.match(page,/id="show-auction" aria-controls="workspace-auction"/);
 assert.match(page,/grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
});
test('weekly and monthly selections request and render distinct OHLC series and adjustment',async()=>{
 const requests=[];const ui=browser(async(_u,o)=>{const b=JSON.parse(o.body);requests.push(b);if(b.name==='get_bars'){const close=b.arguments.interval==='1w'?42:84;return response({...samples.get_bars,interval:b.arguments.interval,adjustment:b.arguments.adjustment,bars:samples.get_bars.bars.map(x=>({...x,open:close-1,close,high:close+1,low:close-2}))});}return response(samples[b.name]);});await ui.ready();
 for(const [mode,close,adjustment] of [['1w',42,'qfq'],['1mo',84,'hfq']]){ui.els.adjustment.value=adjustment;await ui.els.periods.click({target:{closest:()=>({dataset:{mode}})}});await ui.ready();assert.equal(ui.eval('charts.chart.rows.at(-1).close'),close);assert.equal(ui.eval('state.chart.interval'),mode);assert.match(ui.els['chart-readout'].textContent,new RegExp('收 '+close));assert.ok(requests.some(x=>x.name==='get_bars'&&x.arguments.interval===mode&&x.arguments.adjustment===adjustment));assert.ok(requests.some(x=>x.name==='get_macd'&&x.arguments.interval===mode));}
});
test('auction empty, failure and retry replace waiting states with meaningful data status',async()=>{
 let fail=true;const ui=browser(async(_u,o)=>{const b=JSON.parse(o.body);if(b.name==='get_auction'&&fail)return new Response(JSON.stringify({error:{message:'UPSTREAM_HTTP_502'}}),{status:502,headers:{'content-type':'application/json'}});return response(samples[b.name]);});await ui.ready();assert.match(ui.els['auction-badge'].textContent,/不可用/);assert.match(ui.els['auction-readout'].textContent,/502/);assert.doesNotMatch(ui.els['auction-readout'].textContent,/等待/);fail=false;await ui.els['retry-auction'].click();assert.match(ui.els['auction-badge'].textContent,/暂无/);assert.match(ui.els['auction-status'].textContent,/不等于/);assert.match(ui.els['auction-readout'].textContent,/没有可展示/);assert.equal(ui.els['retry-auction'].disabled,false);
});

import {parseAuction} from '../src/worker.mjs';
test('auction uses real time positions for linked price-volume, amount toggle and post-auction readout',async()=>{const d=parseAuction(readFileSync(new URL('./fixtures/eastmoney_premarket.json',import.meta.url),'utf8'),'sh600522',Date.parse('2026-09-30T10:00:00+08:00'));const ui=browser(async(_u,o)=>response(JSON.parse(o.body).name==='get_auction'?d:samples[JSON.parse(o.body).name]));await ui.ready();assert.equal(ui.eval('charts.auction.geometry.positions.length'),16);assert.ok(page.indexOf('id="auction-panel"')>page.indexOf('</aside></div>'));ui.eval('charts.auction.index=11;draw("auction")');assert.match(ui.els['auction-readout'].textContent,/09:26:00.*10,000 股.*202,200.00 元.*竞价后分钟报告/);assert.match(ui.els['auction-summary'].innerHTML,/虚拟匹配量.*来源未提供/);ui.eval('charts.auction.index=10;draw("auction")');assert.match(ui.els['auction-readout'].textContent,/09:25:00.*竞价后分钟报告/);ui.els['auction-measure'].value='amount';ui.els['auction-measure'].change();assert.match(ui.els['auction-table'].innerHTML,/来源报告额（元）/);for(const width of [360,800]){ui.els.auction.clientWidth=width;ui.eval('draw("auction")');assert.equal(ui.els.auction.width,width);assert.equal(ui.eval('charts.auction.geometry.positions[0]'),62);assert.equal(ui.eval('charts.auction.geometry.positions.at(-1)'),width-24);} });
test('cached auction snapshot visibly preserves age and non-live status',async()=>{const d={...parseAuction(readFileSync(new URL('./fixtures/eastmoney_premarket.json',import.meta.url),'utf8'),'sh600522'),cache:{used:true,age_seconds:120},freshness:{status:'cached_snapshot',age_seconds:18000}};const ui=browser(async(_u,o)=>response(JSON.parse(o.body).name==='get_auction'?d:samples[JSON.parse(o.body).name]));await ui.ready();assert.match(ui.els['auction-badge'].textContent,/缓存快照 · 非实时/);assert.match(ui.els['auction-status'].textContent,/本次来源请求失败.*同日快照/);assert.match(ui.els.sources.innerHTML,/缓存 \/ 非实时/);});

test('industry fallback visibly labels unknown date and distinct Sina methodology',async()=>{const ui=browser(async(_u,o)=>{const name=JSON.parse(o.body).name;return response(name==='get_market_context'?{fetched_at:common.fetched_at,indices:[],industry_context:{available:true,source:'sina',leaders:[{name:'电子行业',change_percent:1.2,session_date:null}],laggards:[]}}:samples[name]);});await ui.ready();await ui.els['read-market-context'].click();assert.match(ui.els['market-context-table'].innerHTML,/新浪行业平均涨跌幅/);assert.match(ui.els['market-context-table'].innerHTML,/未提供/);assert.match(ui.els['market-context-table'].innerHTML,/抓取时间不等于数据更新时间/);assert.equal(ui.els['read-market-context'].disabled,false);});
test('quote UI shows source limits without claiming locked book or suspension',async()=>{const d={...samples.get_quotes,quotes:[{...samples.get_quotes.quotes[0],security_status:{limit_up_price:33,limit_down_price:27,price_limit_status:'between_limits'}}]};const ui=browser(async(_u,o)=>response(JSON.parse(o.body).name==='get_quotes'?d:samples[JSON.parse(o.body).name]));await ui.ready();assert.match(ui.els['quote-body'].innerHTML,/涨停价 33.00.*跌停价 27.00/);assert.match(ui.els['quote-body'].innerHTML,/不代表当前封板或可交易；停复牌状态未知/);});

test('stock context is manual with explicit unknown time and partial failure',async()=>{let calls=0;const data={symbol:'sh600522',fetched_at:common.fetched_at,membership:{name:'电子信息',code:'new_dzxx',evidence_url:'https://finance.sina.com.cn/realstock/company/sh600522/nc.shtml'},sector_context:{change_percent:1.2,rank_descending:4,universe_size:49}};const ui=browser(async(_u,o)=>{const n=JSON.parse(o.body).name;if(n==='get_stock_context'){calls++;return response(data);}return response(samples[n]);});await ui.ready();assert.equal(calls,0);await ui.els['read-stock-context'].click();assert.equal(calls,1);assert.match(ui.els['stock-context-body'].innerHTML,/电子信息.*new_dzxx/);assert.match(ui.els['stock-context-body'].innerHTML,/4 \/ 49/);assert.match(ui.els['stock-context-status'].textContent,/归属生效日期与板块更新时间未知/);data.sector_context=null;await ui.els['read-stock-context'].click();assert.match(ui.els['stock-context-body'].innerHTML,/归属与行情分别处理/);assert.doesNotMatch(ui.els['stock-context-body'].innerHTML,/4 \/ 49/);assert.equal(ui.els['read-stock-context'].disabled,false);});
test('new stock selection clears old membership and rejects late old response',async()=>{let finish;const ui=browser(async(_u,o)=>{const n=JSON.parse(o.body).name;return n==='get_stock_context'?new Promise(r=>finish=r):response(samples[n]);});await ui.ready();const pending=ui.els['read-stock-context'].click();ui.els.symbol.value='600584';await ui.submit();finish(response({symbol:'sh600522',membership:{name:'OLD',code:'new_dzxx',evidence_url:'https://finance.sina.com.cn/realstock/company/sh600522/nc.shtml'}}));await pending;assert.equal(ui.els['stock-context-body'].innerHTML,'');assert.match(ui.els['stock-context-status'].textContent,/600584/);assert.equal(ui.els['read-stock-context'].disabled,false);});

