import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {parseHistory,parseIntraday,parseAuction,calculateMACD,bars,macd} from '../src/worker.mjs';
const read=n=>readFileSync(new URL('./fixtures/'+n,import.meta.url),'utf8'),now=Date.parse('2026-09-30T14:06:00+08:00');
test('historical qfq bars exclude unfinished day, week, month, preserve volume and adjustment',()=>{for(const [i,p] of [['1d','day'],['1w','week'],['1mo','month']]){const r=parseHistory(read('tencent_'+p+'.json'),'sh600522',i,120,'qfq',false,now);assert.equal(r.bars.length,120);assert.ok(r.bars.every(x=>x.complete));assert.equal(r.adjustment,'qfq');assert.equal(r.bars.at(-1).amount_cny,null);assert.ok(r.bars.at(-1).date<'2026-09-30');}const r=parseHistory(read('tencent_day.json'),'sh600522','1d',600,'qfq',true,now);assert.equal(r.bars.at(-1).complete,false);assert.equal(r.bars[0].volume_shares,100000);});
test('requested adjusted key cannot silently fall back; negative qfq prices accepted',()=>{const r=JSON.parse(read('tencent_day.json'));r.data.sh600522.qfqday[0][1]='-1';r.data.sh600522.qfqday[0][4]='-2';assert.equal(parseHistory(JSON.stringify(r),'sh600522','1d',600,'qfq',false,now).bars[0].open,-1);assert.throws(()=>parseHistory(JSON.stringify(r),'sh600522','1d',5,'hfq',false,now),/ADJUSTMENT/);});
test('intraday uses successive differences; opening volume not fabricated; amount and average exact',()=>{const r=parseIntraday(read('tencent_minute.json'),'sh600522',false,now);assert.equal(r.points[0].cumulative_volume_shares,100000);assert.equal(r.points[0].interval_volume_shares,null);assert.equal(r.points[1].interval_minutes,1);assert.equal(r.points[1].interval_volume_shares,(1100-1000)*100);assert.equal(r.points[0].average_price_cny,2000000/100000);});
test('STAR shares, missing Beijing amounts, CDR unverified units and partial-point filter',()=>{const make=(s,rows)=>JSON.stringify({code:0,data:{[s]:{data:{date:'20260930',data:rows}}}});assert.equal(parseIntraday(make('sh688981',['0930 117.77 44991 5298590.00']),'sh688981',false,now).points[0].cumulative_volume_shares,44991);const bj=parseIntraday(make('bj920002',['0930 51.56 209']),'bj920002',false,now).points[0];assert.equal(bj.cumulative_amount_cny,null);assert.equal(bj.average_price_cny,null);assert.equal(bj.cumulative_volume_shares,20900);assert.throws(()=>parseIntraday(make('sh689009',['0930 1 1']),'sh689009',false,now),/UNIT_UNVERIFIED/);assert.throws(()=>parseIntraday(make('sh600522',['1406 31 10 31000']),'sh600522',false,now),/NO_COMPLETED/);});
test('auction retains09:26 execution evidence and never labels09:25 final match or zero unmatched',()=>{const r=parseAuction(read('eastmoney_premarket.json'),'sh600522',now);assert.equal(r.points.length,16);const p=r.points.find(x=>x.source_timestamp.includes('09:26'));assert.equal(p.reported_volume_shares,10000);assert.equal(p.reported_amount_cny,202200);assert.equal(p.final_match_price,null);assert.equal(r.points[0].unmatched_buy_shares,null);assert.equal(r.capabilities.full_auction_feed,false);});
test('EMA12/26/9 against closed form ramp expected, Chinese doubled histogram and constant input',()=>{const input=Array.from({length:301},(_,i)=>({close:100+i,complete:true,source_timestamp:String(i)}));const out=calculateMACD(input);for(const i of [1,2,20,100,300]){const expected=(12.5*(1-(25/27)**i)-5.5*(1-(11/13)**i));assert.ok(Math.abs(out[i].dif-expected)<1e-10);let dea=0;for(let j=1;j<=i;j++)dea=.8*dea+.2*(12.5*(1-(25/27)**j)-5.5*(1-(11/13)**j));assert.ok(Math.abs(out[i].dea-dea)<1e-10);assert.ok(Math.abs(out[i].macd_histogram-2*(expected-dea))<1e-10);}assert.ok(calculateMACD(input.map(x=>({...x,close:8}))).every(x=>x.dif===0&&x.dea===0&&x.macd_histogram===0));});
test('MACD warmup is explicitly limited for minute bars; unsupported adjustment rejects',async()=>{await assert.rejects(()=>bars({symbol:'600522',interval:'1m',adjustment:'qfq'}),/MINUTE_ADJUSTMENT/);const saved=globalThis.fetch,savedNow=Date.now;try{Date.now=()=>now;globalThis.fetch=async()=>new Response(read('tencent_day.json'));const r=await macd({symbol:'600522',interval:'1d',adjustment:'qfq',limit:100});assert.equal(r.parameters.warmup_bars,220);assert.equal(r.parameters.seed_sensitive,true);assert.equal(r.points.length,100);}finally{globalThis.fetch=saved;Date.now=savedNow;}});

import {page} from '../src/page.mjs';import vm from 'node:vm';test('chart script compiles and includes actual canvas price and volume rendering',()=>{new vm.Script(page.match(/<script>([\s\S]*)<\/script>/)[1]);assert.ok(page.includes('getContext'));assert.ok(page.includes('interval_volume_shares'));});
import {parseTencent,parseSina} from '../src/worker.mjs';
test('synthetic STAR quote normalization across schema fixtures; rounded book remains lots',()=>{const a=parseTencent(read('tencent_star_quote.txt'),'sh688981'),b=parseSina(read('sina_star_quote.txt'),'sh688981');assert.equal(a.volume_shares,1234500);assert.ok(Math.abs(a.volume_shares-b.volume_shares)/b.volume_shares<.001);assert.equal(a.book.bids[0].volume_shares,1000);assert.equal(b.book.bids[0].volume_shares,1003);});

test('adjusted current-day bars can be schedule-complete after conservative postclose boundary, final revisions remain unknown',()=>{const t=Date.parse('2026-09-30T16:00:00+08:00');const r=parseHistory(read('tencent_day.json'),'sh600522','1d',600,'qfq',true,t);assert.equal(r.bars.at(-1).complete,true);assert.equal(r.bars.at(-1).calendar_completion,true);assert.equal(r.source_finality,'unknown');});

import {auction} from '../src/worker.mjs';
test('auction requests own public endpoint without unrelated Sina request headers',async()=>{const saved=globalThis.fetch;try{globalThis.fetch=async(url,options)=>{assert.match(url,/^https:\/\/push2delay\.eastmoney\.com\//);assert.deepEqual(options.headers,{});assert.equal(options.redirect,'manual');return new Response(read('eastmoney_premarket.json'));};const r=await auction({symbol:'600522'});assert.equal(r.points.length,16);assert.equal(r.capabilities.full_auction_feed,false);assert.equal(r.points[0].final_match_price,null);}finally{globalThis.fetch=saved;}});
