import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import worker,{symbol,parseTencent,parseSina,parseBars,tools,quotes}from'../src/worker.mjs';
const base=new URL('./fixtures/',import.meta.url).pathname;const tx=readFileSync(base+'tencent_snapshot.txt','utf8'),sn=readFileSync(base+'sina_snapshot.txt','utf8');
test('symbol validation prevents arbitrary URLs and non A-shares',()=>{assert.equal(symbol('600522.SH'),'sh600522');assert.equal(symbol('000001'),'sz000001');assert.equal(symbol('920002'),'bj920002');for(const x of ['https://evil.cn','sh000001','hk00700','sh600522&x=y','../../a'])assert.throws(()=>symbol(x));});
test('Tencent quote unit normalization agrees with near-time Sina shares/amount',()=>{const a=parseTencent(tx,'sh600522'),b=parseSina(sn,'sh600522');assert.equal(a.volume_shares,10000000);assert.equal(a.amount_cny,200000000);assert.ok(Math.abs(a.volume_shares-b.volume_shares)/b.volume_shares<0.0001);assert.ok(Math.abs(a.amount_cny-b.amount_cny)/b.amount_cny<0.0001);assert.equal(a.book.bids[0].volume_shares,1000);assert.equal(a.book.source,a.source);});
test('13:45-labelled five minute bar excluded at 13:43',()=>{const raw=readFileSync(base+'sina_600522_5min.txt','utf8');const a=parseBars(raw,'sh600522','5m',240,false,Date.parse('2026-09-30T13:43:30+08:00'));assert.equal(a.bars.at(-1).source_timestamp,'2026-09-30T13:40:00+08:00');assert.ok(a.bars.every(x=>x.complete));const b=parseBars(raw,'sh600522','5m',240,true,Date.parse('2026-09-30T13:43:30+08:00'));assert.equal(b.bars.at(-1).complete,false);});
test('unauthenticated calls rejected; discovery exposes thirteen read-only tools',async()=>{const call=await worker.fetch(new Request('https://test/mcp',{method:'POST',body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'get_quotes',arguments:{symbols:['600522']}}})}));assert.equal(call.status,401);assert.equal(tools.length,14);assert.ok(tools.every(t=>t.annotations.readOnlyHint));});

test('bar received after boundary cannot become complete retroactively',()=>{const raw=readFileSync(base+'sina_600522_5min.txt','utf8');const a=parseBars(raw,'sh600522','5m',240,false,Date.parse('2026-09-30T13:45:05+08:00'),Date.parse('2026-09-30T13:44:59+08:00'));assert.equal(a.bars.at(-1).source_timestamp,'2026-09-30T13:40:00+08:00');assert.equal(a.fetched_at,'2026-09-30T05:45:05.000Z');});

test('null and array RPC bodies produce invalid-request errors',async()=>{for(const body of ['null','[]','{"jsonrpc":"2.0","method":1}','{"jsonrpc":"2.0","method":"ping","id":{}}']){const r=await worker.fetch(new Request('https://test/mcp',{method:'POST',body}));assert.equal(r.status,400);assert.equal((await r.json()).error.code,-32600);}});

test('parallel routing retains newer stale source and reports older/failing alternate',async()=>{const realFetch=globalThis.fetch,realNow=Date.now;Date.now=()=>Date.parse('2026-09-30T13:50:00+08:00');try{for(const mode of ['older','failed','future']){globalThis.fetch=async u=>{if(String(u).includes('qt.gtimg.cn'))return new Response(tx);if(mode==='failed')return new Response('',{status:503});return new Response(mode==='older'?sn.replaceAll('2026-09-30','2026-09-29'):sn.replaceAll('13:43:09','14:43:09'));};const r=await quotes({symbols:['600522']});assert.equal(r.quotes[0].source,'tencent');assert.equal(r.quotes[0].freshness.status,'stale');assert.equal(r.quotes[0].selection_reason,'NEWEST_VALID_BUT_STALE');assert.equal(r.quotes[0].candidates.length,2);}}finally{globalThis.fetch=realFetch;Date.now=realNow;}});

test('edge-compatible fetch manually rejects redirects without following',async()=>{const realFetch=globalThis.fetch;let calls=0;try{globalThis.fetch=async (u,opts)=>{calls++;assert.equal(opts.redirect,'manual');return new Response('',{status:302,headers:{location:'https://example.invalid/'}});};const r=await quotes({symbols:['600522']});assert.equal(r.quotes[0].error.code,'QUOTE_UNAVAILABLE');assert.match(r.quotes[0].error.message,/UPSTREAM_REDIRECT_REJECTED/);assert.equal(calls,2);}finally{globalThis.fetch=realFetch;}});
