import test from'node:test';import assert from'node:assert/strict';
import{createPublicMainboardDirectoryReader,parseSseMainboard,parseSzseMainboardMetadata,parseSzseMainboardWorkbook,assemblePublicMainboardDirectory,PUBLIC_DIRECTORY_SOURCES,PUBLIC_DIRECTORY_LIMITS}from'../src/public-mainboard-directory.mjs';
import{buildPublicMainboardUniverse}from'../src/mainboard-universe.mjs';
import{sseRoot,szMetadata,workbook,xlsx,STAMP,SSE_ROWS,SZ_ROWS}from'./fixtures/public-directory-fixtures.mjs';
const now=Date.parse(STAMP),response=(d,type='application/json')=>new Response(typeof d==='object'&&!(d instanceof Uint8Array)?JSON.stringify(d):d,{headers:{'content-type':type}});
function mock(calls=[]){return async(url,o)=>{calls.push({url,options:o});assert.ok(Object.values(PUBLIC_DIRECTORY_SOURCES).some(s=>s.url===url));assert.equal(o.method,'GET');assert.equal(o.credentials,'omit');assert.equal(o.redirect,'manual');for(const[k,v]of Object.entries(o.headers??{}))assert.ok(!/cookie|authorization|key|token/i.test(k+':'+v));if(url===PUBLIC_DIRECTORY_SOURCES.sse.url)return response(sseRoot());if(url===PUBLIC_DIRECTORY_SOURCES.szse_metadata.url)return response(szMetadata());return response(xlsx(),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');};}
test('public parsers preserve six-digit IDs/names/list dates, official mainboard scope and count reconciliation',async()=>{const sse=parseSseMainboard(sseRoot()),meta=parseSzseMainboardMetadata(szMetadata()),sz=parseSzseMainboardWorkbook(workbook(),meta);const dir=assemblePublicMainboardDirectory(sse,sz,meta,{sseFetchedAt:STAMP,szseFetchedAt:STAMP,metadataFetchedAt:STAMP,now});const result=await buildPublicMainboardUniverse(dir,{now});assert.equal(result.available,true);assert.equal(result.source,'sse_szse_public');assert.equal(result.credential_reads,false);assert.equal(result.source_timestamp,null);assert.match(result.snapshot_timestamp_semantics,/receipt_identifier_not_membership/);assert.equal(result.coverage.provider_rows,4);assert.equal(result.coverage.eligible_mainboard_non_st,2);assert.equal(result.coverage.excluded_st_name,2);assert.deepEqual(result.items.map(r=>r.symbol),['sh600522','sz000001']);assert.equal(result.coverage.complete_exchange_universe,false);assert.match(result.manifest_hash,/^[a-f0-9]{64}$/);});
test('SSE incomplete/count/duplicate/scope/duplicate payload contradictions fail closed',()=>{for(const mutate of [r=>{r.pageHelp.total++},r=>{r.pageHelp.pageCount=2},r=>{r.result[0].LIST_BOARD='2'},r=>{r.pageHelp.data[0].SEC_NAME_CN='different'},r=>{r.result[1]=r.result[0];r.pageHelp.data[1]=r.result[0]},r=>{r.actionErrors=['failure']},r=>{r.result[0].A_STOCK_CODE='60052';r.pageHelp.data[0].A_STOCK_CODE='60052'}]){const r=sseRoot();mutate(r);assert.throws(()=>parseSseMainboard(r));}});
test('SZ metadata scope/date/first-page shape and workbook headers/count/identity are validated without 75-page traversal',()=>{for(const mutate of [r=>{r[0].metadata.recordcount++},r=>{r[0].metadata.conditions[0].defaultValue='nm'},r=>{r[0].metadata.subname='not-a-date'},r=>{r[0].error='failure'},r=>{r.push(structuredClone(r[0]))}]){const r=szMetadata();mutate(r);assert.throws(()=>parseSzseMainboardMetadata(r));}const meta=parseSzseMainboardMetadata(szMetadata());for(const w of [workbook(SZ_ROWS.slice(1)),{sheetName:'wrong',rows:workbook().rows},{sheetName:'A股列表',rows:[['板块','A股代码','A股代码','A股上市日期'],...SZ_ROWS]},workbook([['创业板','000001','fixture-sz','1991-04-03'],SZ_ROWS[1]]),workbook([['主板','000001','different','1991-04-03'],SZ_ROWS[1]])])assert.throws(()=>parseSzseMainboardWorkbook(w,meta));});
test('cold read is exactly3 fixed credential-free GETs, both sources succeed before any universe; cache is public-only original-time preserving',async()=>{let clock=now;const calls=[],read=createPublicMainboardDirectoryReader({fetchImpl:mock(calls),now:()=>clock});const d=await read();assert.equal(d.available,true);assert.equal(calls.length,3);assert.equal(d.cache.kind,'fetched');assert.equal(d.cache.current_call_started_outbound_requests,3);clock+=10000;const cached=await read();assert.equal(calls.length,3);assert.equal(cached.cache.used,true);assert.equal(cached.cache.kind,'fresh_cached');assert.equal(cached.cache.current_call_started_outbound_requests,0);assert.equal(cached.snapshot_timestamp,d.snapshot_timestamp);assert.equal(cached.fetched_at,d.fetched_at);assert.notEqual(cached.served_at,d.served_at);const a=await buildPublicMainboardUniverse(d,{now}),b=await buildPublicMainboardUniverse(cached,{now:clock});assert.equal(a.manifest_hash,b.manifest_hash);});
test('concurrent callers share one three-request refresh and mutate neither cached rows nor other responses',async()=>{let release;const gate=new Promise(r=>release=r),calls=[],fetch=mock(calls),read=createPublicMainboardDirectoryReader({fetchImpl:async(...args)=>{await gate;return fetch(...args);},now:()=>now});const a=read(),b=read();release();const [first,second]=await Promise.all([a,b]);assert.equal(calls.length,3);assert.equal(second.cache.shared_inflight,true);assert.equal(second.cache.current_call_started_outbound_requests,0);first.items[0].name='modified';const third=await read();assert.notEqual(third.items[0].name,'modified');});
test('source403/429/redirect/wrong MIME/body cap fail without partial universe, key fallback, retry or repeated requests during cooldown',async()=>{for(const make of [()=>new Response('forbidden',{status:403}),()=>new Response('limited',{status:429}),()=>new Response('',{status:302}),()=>new Response('<html>',{headers:{'content-type':'text/html'}}),()=>new Response('X',{headers:{'content-type':'application/json','content-length':String(PUBLIC_DIRECTORY_LIMITS.sse_bytes+1)}})]){let count=0;const read=createPublicMainboardDirectoryReader({fetchImpl:async()=>{count++;return make()},now:()=>now});const d=await read();assert.equal(d.available,false);assert.equal(d.coverage,null);assert.deepEqual(d.items,[]);assert.equal(count,3);const next=await read();assert.equal(count,3);assert.ok(next.diagnostics.retry_after_seconds>0);assert.equal(next.credential_reads,false);}});
test('expired successful cache only falls back within age and same Shanghai day, flagged and original timestamps retained',async()=>{let clock=now,fail=false;const calls=[],fetch=mock(calls),read=createPublicMainboardDirectoryReader({fetchImpl:(...args)=>fail?Promise.reject(Error('fixture_failure')):fetch(...args),now:()=>clock,limits:{...PUBLIC_DIRECTORY_LIMITS,cache_ttl_ms:1000,failure_cooldown_ms:100}});const d=await read();clock+=2000;fail=true;const f=await read();assert.equal(f.available,true);assert.equal(f.cache.kind,'stale_fallback');assert.equal(f.fetched_at,d.fetched_at);assert.equal(f.cache.current_call_started_outbound_requests,3);assert.ok(f.warnings.includes('CACHED_PUBLIC_DIRECTORY_REFRESH_FAILED_NOT_FRESH'));clock+=10;const c=await read();assert.equal(c.cache.current_call_started_outbound_requests,0);clock=Date.parse('2026-10-04T01:00:00Z');const expired=await read();assert.equal(expired.available,false);assert.equal(expired.coverage,null);});
test('bounded stalled sources time out, no retry or leaked upstream error text, and parser failures do not cache partial results',async()=>{let calls=0;const read=createPublicMainboardDirectoryReader({fetchImpl:()=>{calls++;return new Promise(()=>{})},now:()=>now,limits:{...PUBLIC_DIRECTORY_LIMITS,source_timeout_ms:10,total_timeout_ms:20}});const d=await read();assert.equal(d.available,false);assert.equal(calls,3);assert.equal(d.diagnostics.code,'PUBLIC_DIRECTORY_TIMEOUT');const bad=createPublicMainboardDirectoryReader({fetchImpl:async()=>{throw Error('PRIVATE_OR_UPSTREAM_RAW_TEXT')},now:()=>now});assert.ok(!JSON.stringify(await bad()).includes('PRIVATE_OR_UPSTREAM_RAW_TEXT'));});
test('public builder rejects receipt/source-time lies, wrong hosts/source counts and duplicate identities',async()=>{const read=createPublicMainboardDirectoryReader({fetchImpl:mock(),now:()=>now}),d=await read();for(const mutate of [r=>{r.source_timestamp=STAMP},r=>{r.snapshot_timestamp_semantics='source_effective_time'},r=>{r.sources[0].host='evil.test'},r=>{r.sources[0].rows++},r=>{r.items[1]=r.items[0]},r=>{r.items[0].source_id='hithink'},r=>{r.credential_reads=true}]){const value=structuredClone(d);mutate(value);const r=await buildPublicMainboardUniverse(value,{now});assert.equal(r.available,false);assert.equal(r.coverage,null);assert.deepEqual(r.items,[]);}});

test('manifest hash is independent of source-array and item order; pagination/date provenance remains observable',async()=>{const read=createPublicMainboardDirectoryReader({fetchImpl:mock(),now:()=>now}),d=await read(),a=await buildPublicMainboardUniverse(d,{now});const reversed=structuredClone(d);reversed.sources.reverse();reversed.items.reverse();const b=await buildPublicMainboardUniverse(reversed,{now});assert.equal(a.manifest_hash,b.manifest_hash);assert.equal(a.sources[0].pagination.pagesize,2000);assert.equal(a.sources[0].pagination.total,2);assert.equal(a.sources[1].metadata_pagination.pages_requested,1);assert.equal(a.sources[1].metadata_pagination.recordcount,2);});

test('native XLSX parse failure is a fixed recoverable category without raw error reflection or partial/cached success',async()=>{const read=createPublicMainboardDirectoryReader({fetchImpl:mock(),parseXlsx:async()=>{throw Error('RAW_XML_OR_UPSTREAM_DETAIL')},now:()=>now});const d=await read();assert.equal(d.available,false);assert.equal(d.diagnostics.code,'PUBLIC_DIRECTORY_XLSX_PARSE_FAILED');assert.equal(d.coverage,null);assert.ok(!JSON.stringify(d).includes('RAW_XML'));});

test('each fixed source403 retains safe source ID, integer HTTP status and original clocks without reflecting provider content',async()=>{
 for(const source of Object.values(PUBLIC_DIRECTORY_SOURCES)){
  let clock=now,calls=0;const good=mock();const read=createPublicMainboardDirectoryReader({fetchImpl:async(url,opts)=>{calls++;if(url===source.url)return new Response('PRIVATE_RESPONSE_BODY',{status:403,headers:{'X-private-header':'PRIVATE_HEADER'}});return good(url,opts);},now:()=>clock});
  const failed=await read();assert.equal(failed.available,false);assert.equal(failed.diagnostics.code,'PUBLIC_DIRECTORY_HTTP_403');assert.equal(failed.diagnostics.source_id,source.id);assert.equal(failed.diagnostics.http_status,403);assert.equal(failed.diagnostics.request_started_at,STAMP);assert.equal(failed.diagnostics.failure_observed_at,STAMP);assert.equal(failed.cache.kind,'failed_refresh');assert.equal(failed.cache.current_call_started_outbound_requests,3);assert.equal(calls,3);
  clock+=1000;const cooldown=await read();assert.equal(cooldown.diagnostics.request_started_at,STAMP);assert.equal(cooldown.diagnostics.failure_observed_at,STAMP);assert.equal(cooldown.cache.kind,'failure_cooldown');assert.equal(cooldown.cache.current_call_started_outbound_requests,0);assert.equal(calls,3);
  const projected=await buildPublicMainboardUniverse(cooldown,{now:clock});assert.equal(projected.diagnostics.source_id,source.id);assert.equal(projected.cache.kind,'failure_cooldown');assert.equal(projected.coverage,null);assert.equal(projected.served_at,new Date(clock).toISOString());
  assert.doesNotMatch(JSON.stringify(projected),/PRIVATE_RESPONSE_BODY|PRIVATE_HEADER|X-private-header|sqlId|SHOWTYPE/);
 }
});

test('network errors cannot forge a source, status, time or credential-bearing diagnostics',async()=>{
 const read=createPublicMainboardDirectoryReader({fetchImpl:async()=>{const e=Error('PRIVATE_ERROR_TEXT');e.source_id='evil-private-source';e.http_status='403-secret';e.request_started_at='PRIVATE_TIME';throw e;},now:()=>now});
 const failed=await read();assert.equal(failed.diagnostics.code,'PUBLIC_DIRECTORY_REQUEST_OR_PARSE_FAILED');assert.equal(failed.diagnostics.source_id,'sse_public_mainboard');assert.equal(failed.diagnostics.http_status,null);assert.equal(failed.diagnostics.request_started_at,STAMP);assert.doesNotMatch(JSON.stringify(failed),/PRIVATE_ERROR|private-source|403-secret|PRIVATE_TIME/);
 const prefixed=createPublicMainboardDirectoryReader({fetchImpl:async()=>{throw Error('XLSX_PRIVATE_CANARY_ABC123');},now:()=>now});const safe=await prefixed();assert.equal(safe.diagnostics.code,'PUBLIC_DIRECTORY_REQUEST_OR_PARSE_FAILED');assert.doesNotMatch(JSON.stringify(safe),/XLSX_PRIVATE_CANARY/);
});
