import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {parseSectors,sectorContext,SECTOR_BASE,parseSinaSectors,SINA_SECTORS} from '../src/sector-context.mjs';import {marketContext} from '../src/market-context.mjs';
const raw=readFileSync(new URL('./fixtures/eastmoney_sectors.json',import.meta.url),'utf8'),now=Date.parse('2026-09-30T16:00:00+08:00');
test('synthetic industry fixture decodes percent without guessed timestamps or volume units',()=>{const d=parseSectors(raw,'leaders',now);assert.equal(d.provider_total,500);assert.equal(d.returned,10);assert.equal(d.sectors[0].name,'合成行业0');assert.equal(d.sectors[0].change_percent,5);assert.equal(d.sectors[0].source_timestamp,null);assert.equal(d.sectors[0].freshness.status,'unknown');assert.equal(d.sectors[0].volume_shares,undefined);});
test('invalid identity duplicates order dates and placeholders never become sector data',()=>{for(const mutate of [d=>d.data.diff[0].f13=1,d=>d.data.diff[1].f12=d.data.diff[0].f12,d=>d.data.diff[0].f3='-',d=>d.data.diff.reverse(),d=>d.data.diff[0].f297=20261001]){const d=JSON.parse(raw);mutate(d);assert.throws(()=>parseSectors(JSON.stringify(d),'leaders',now));}});
test('top and bottom requests fail independently with explicit partial coverage',async()=>{let urls=[];const d=await sectorContext(async url=>{urls.push(url);if(url.endsWith('po=0'))throw Error('UPSTREAM_HTTP_502');return raw;},()=>now);assert.equal(d.available,true);assert.equal(d.leaders.length,10);assert.equal(d.laggards.length,0);assert.match(d.requests[1].error,/502/);assert.equal(urls.length,3);assert.ok(urls.every(u=>u.startsWith(SECTOR_BASE)||u===SINA_SECTORS));});
test('sector failure leaves benchmarks and benchmark failure leaves sector results',async()=>{const d=await marketContext(async url=>{if(url.includes('qt.gtimg'))throw Error('UPSTREAM_TIMEOUT');if(url.endsWith('po=0')){const o=JSON.parse(raw);o.data.diff.reverse();return JSON.stringify(o);}return raw;},()=>now);assert.equal(d.indices.filter(i=>i.error).length,6);assert.equal(d.industry_context.available,true);});

test('Sina fallback preserves entire classification and missing time as unknown',async()=>{const raw=readFileSync(new URL('./fixtures/sina_sectors.txt',import.meta.url),'utf8');const d=parseSinaSectors(raw,now);assert.ok(d.provider_total>40);assert.equal(d.sectors[0].source_timestamp,null);assert.equal(d.sectors[0].session_date,null);assert.equal(d.sectors[0].index_points,null);const result=await sectorContext(async url=>{if(url===SINA_SECTORS)return raw;throw Error('UPSTREAM_TIMEOUT');},()=>now);assert.equal(result.source,'sina');assert.equal(result.leaders.length,10);assert.equal(result.laggards.length,10);assert.ok(result.leaders.every(r=>r.source==='sina'));assert.ok(result.leaders[0].change_percent>=result.laggards[0].change_percent);});

import {contextFetchText} from '../src/context-fetch.mjs';
test('context fetch is bounded through body and rejects redirect without retry',async()=>{let calls=0;await assert.rejects(contextFetchText('https://test.invalid',{timeoutMs:10,fetchImpl:async()=>{calls++;return {ok:true,status:200,arrayBuffer:()=>new Promise(()=>{})};}}),/TIMEOUT/);assert.equal(calls,1);await assert.rejects(contextFetchText('https://test.invalid',{fetchImpl:async()=>new Response('',{status:302})}),/REDIRECT/);});
test('empty and malformed industry responses remain unavailable instead of fabricated lists',async()=>{for(const raw of ['null','{}','{"rc":0,"data":{"total":0,"diff":[]}}','var S_Finance_bankuai_sinaindustry = {};','var S_Finance_bankuai_sinaindustry = {"new_a":"bad"};']){assert.throws(()=>parseSinaSectors(raw,now));assert.throws(()=>parseSectors(raw,'leaders',now));}const d=await sectorContext(async()=>'{"rc":0,"data":{"total":0,"diff":[]}}',()=>now);assert.equal(d.available,false);assert.deepEqual(d.leaders,[]);assert.deepEqual(d.laggards,[]);});
