import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateSwingHistory,runSwingScreen,validateSwingArguments,swingThresholds,SWING_DEFAULTS,SWING_LIMITS,expectedSwingSession} from '../src/swing-screening.mjs';
import {tradingDay} from '../src/market-session.mjs';
import worker,{callData,symbol,tools,VERSION} from '../src/worker.mjs';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
const NOW=Date.parse('2026-10-01T12:00:00+08:00');
const add=(d,n)=>new Date(Date.parse(d+'T00:00:00Z')+86400000*n).toISOString().slice(0,10);
function history({n=80,kind='mature',last='2026-09-30',volume=100}={}){const dates=[];for(let d=last;dates.length<n;d=add(d,-1))if(tradingDay(d))dates.unshift(d);return {symbol:'sh600000',source:'tencent',adjustment:'qfq',interval:'1d',cache:{used:false},fetched_at:new Date(NOW).toISOString(),unit_notes:{volume:'synthetic shares, not real data'},bars:dates.map((date,i)=>{const close=kind==='flat'?100:kind==='early'?(i<n-30?200-i:100+(i-(n-30))*0.5):100+i;return {date,source_timestamp:date+'T15:00:00+08:00',open:close,high:close+.1,low:close-.1,close,volume_shares:i===n-1?volume:100,amount_cny:null,complete:true};})};}
const evalAt=(d,extra={})=>evaluateSwingHistory(d,{now:NOW,...extra});
const clone=x=>JSON.parse(JSON.stringify(x));
test('frozen defaults and bounded runtime arguments, code dedup without mutation or guessed names',()=>{assert.deepEqual(SWING_DEFAULTS,{breakout_volume_ratio:1.5,continuation_volume_ratio:.8,continuation_near_high_pct:5,max_extension_ma20_pct:12,max_return_5d_pct:20});for(const a of [{symbols:[]},{symbols:Array(21).fill('600000')},{symbols:['600000'],owner:'else'},{symbols:['600000'],after:'600000'},{universe:'original_watchlist',symbols:['600000']},{universe:'all_market'}, {symbols:['600000'],thresholds:{breakout_volume_ratio:0}},{symbols:['600000'],thresholds:{breakout_volume_ratio:'1.5'}},{symbols:['600000'],thresholds:{ma20:10}},{symbols:[{}]}])assert.throws(()=>validateSwingArguments(a,symbol));const a=validateSwingArguments({symbols:['600000','sh600000','新华传媒','https://evil']},symbol);assert.equal(a.items.length,3);assert.equal(a.deduplicated_count,1);assert.equal(a.items[1].error,'INVALID_SYMBOL');assert.equal(a.items[2].error,'INVALID_SYMBOL');for(const v of [null,[],{x:1},{max_return_5d_pct:Infinity}])assert.throws(()=>swingThresholds(v));});
test('mature continuation takes priority while preserving breakout match; early serial breakout can match despite falling MA60',()=>{const mature=evalAt(history({volume:150}));assert.equal(mature.status,'match');assert.equal(mature.phase,'continuation');assert.equal(mature.checks.emerging.matched,true);assert.equal(mature.breakout_kind,'repeated');const early=evalAt(history({kind:'early',volume:150}));assert.equal(early.status,'match');assert.equal(early.phase,'emerging');assert.equal(early.checks.continuation.conditions.ma60_rising,false);assert.equal(early.breakout_kind,'repeated');assert.equal(early.sample.used_count,65);});
test('flat equality does not count as price/MA increase or breakout and rule failure is not missing data',()=>{const d=history({kind:'flat'});for(const b of d.bars)b.high=b.close;const r=evalAt(d);assert.equal(r.status,'not_match');assert.equal(r.metrics.ma20,100);assert.equal(r.checks.emerging.conditions.above_ma20,false);assert.equal(r.checks.emerging.conditions.breakout_prior20,false);assert.equal(r.checks.continuation.conditions.ma_alignment,false);assert.equal(r.security_status.suspension,'unknown');});
test('volume threshold equality passes; breakout strict high equality fails; continuation near-high equality passes',()=>{let d=history({kind:'early',volume:150}),r=evalAt(d);assert.equal(r.metrics.volume_ratio20,1.5);assert.equal(r.checks.emerging.conditions.breakout_volume,true);d.bars.at(-1).volume_shares=149.999;assert.equal(evalAt(d).status,'not_match');d=history({kind:'early',volume:150});d.bars.at(-2).high=d.bars.at(-1).close;assert.equal(evalAt(d).checks.emerging.conditions.breakout_prior20,false);d=history();const target=d.bars.at(-1).close/.95;d.bars.at(-2).high=target;r=evalAt(d);assert.equal(r.checks.continuation.conditions.near_prior20_high,true);d.bars.at(-2).high=target+.001;assert.equal(evalAt(d).checks.continuation.conditions.near_prior20_high,false);});
test('prior high and volume exclude signal bar, and overextension flags do not drop a match',()=>{const d=history({kind:'early',volume:150});Object.assign(d.bars.at(-1),{close:150,open:150,high:999,low:140,volume_shares:300});const r=evalAt(d);assert.equal(r.metrics.prior_mean_volume20,100);assert.equal(r.metrics.volume_ratio20,3);assert.equal(r.metrics.prior_high20,d.bars.at(-2).high);assert.equal(r.metrics.prior_high20_last_date,d.bars.at(-2).date);assert.equal(r.status,'match');assert.deepEqual(r.risk_flags,['OVEREXTENDED_MA20','RAPID_5_BAR_ADVANCE']);assert.equal(r.metrics.amount_cny,null);const equal=evalAt(d,{thresholds:{max_extension_ma20_pct:r.metrics.extension_ma20_pct,max_return_5d_pct:r.metrics.return_5d_pct}});assert.deepEqual(equal.risk_flags,[]);});
test('incomplete, same-day and future bars cannot change fixed-cutoff metrics or classes',()=>{const d=history(),base=evalAt(d);for(const date of ['2026-10-01','2026-10-08','2026-10-09'])d.bars.push({...d.bars.at(-1),date,source_timestamp:date+'T15:00:00+08:00',close:999,high:999,open:999,low:999,volume_shares:999999,complete:true});const r=evalAt(d);assert.deepEqual(r.metrics,base.metrics);assert.deepEqual(r.checks,base.checks);assert.equal(r.phase,base.phase);assert.equal(r.sample.excluded_current_date,1);assert.equal(r.sample.excluded_future,2);const missing=history();missing.bars.at(-1).complete=false;assert.equal(evalAt(missing).reason_codes[0],'STALE_DAILY_HISTORY');});
test('today is eligible after verified postclose boundary; preopen and known holiday freshness use prior session',()=>{const d=history(),after=Date.parse('2026-09-30T18:00:00+08:00');assert.equal(evaluateSwingHistory(d,{now:after}).sample.last_date,'2026-09-30');assert.equal(evaluateSwingHistory(d,{now:after}).freshness.expected_session_date,'2026-09-30');assert.equal(expectedSwingSession(Date.parse('2026-10-07T23:59:00+08:00')),'2026-09-30');assert.equal(expectedSwingSession(Date.parse('2026-09-30T09:00:00+08:00')),'2026-09-29');assert.equal(expectedSwingSession(Date.parse('2027-01-01T12:00:00+08:00')),null);});
test('invalid/mixed/stale/cached/negative/missing/duplicate data never produce a fabricated no-match',()=>{const cases=[['INVALID_HISTORY_BASIS',d=>d.adjustment='none'],['INVALID_HISTORY_BASIS',d=>d.source='sina'],['INVALID_HISTORY_BASIS',d=>d.cache.used=true],['MIXED_HISTORY_BASIS',d=>d.bars.at(-1).adjustment='none'],['INVALID_HISTORY_VALUES',d=>d.bars.at(-1).close=null],['INVALID_HISTORY_VALUES',d=>d.bars.at(-1).volume_shares=null],['INVALID_HISTORY_VALUES',d=>d.bars.at(-1).low=-1],['INVALID_HISTORY_VALUES',d=>d.bars.at(-1).high=1],['INVALID_HISTORY_DATE',d=>d.bars.at(-1).date='2026-02-30'],['DUPLICATE_HISTORY_DATE',d=>d.bars.push({...d.bars.at(-1)})],['STALE_DAILY_HISTORY',d=>d.bars.pop()],['MISSING_SCHEDULED_SESSIONS',d=>d.bars.splice(-6,1)],['NONPOSITIVE_VOLUME_BASELINE',d=>d.bars.forEach(b=>b.volume_shares=0)]];for(const [code,change] of cases){const d=history();change(d);const r=evalAt(d);assert.equal(r.status,'insufficient_data',code);assert.equal(r.reason_codes[0],code);assert.equal(r.metrics,null);}});
test('unknown calendar and minimum-history floor are explicit; sort checks preserve exact metrics',()=>{const d=history();assert.equal(evaluateSwingHistory(d,{now:Date.parse('2027-01-01T12:00:00+08:00')}).reason_codes[0],'UNKNOWN_CALENDAR');assert.equal(evalAt(history({n:64})).reason_codes[0],'INSUFFICIENT_COMPLETED_BARS');const base=evalAt(d);d.bars.reverse();const r=evalAt(d);assert.deepEqual(r.metrics,base.metrics);assert.equal(r.sample.reordered,true);d.bars.unshift({...d.bars[0],date:'2025-12-31',source_timestamp:'2025-12-31T15:00:00+08:00'});assert.equal(evalAt(d).sample.excluded_unknown_calendar,1);});
test('per-symbol source failure, invalid symbol, deterministic order, and bounded concurrency',async()=>{let running=0,max=0,calls=0;const r=await runSwingScreen({symbols:['600000','bad','600001','600000','600002','600003']},{normalize:symbol,now:()=>NOW,loadHistory:async s=>{calls++;running++;max=Math.max(max,running);await new Promise(resolve=>setTimeout(resolve,2));running--;if(s==='sh600001')throw Error('UPSTREAM_HTTP_503');return {...history(),symbol:s};}});assert.equal(calls,4);assert.equal(max,3);assert.deepEqual(r.results.map(r=>r.symbol),['sh600000',null,'sh600001','sh600002','sh600003']);assert.deepEqual(r.summary,{match:3,not_match:0,insufficient_data:2});assert.equal(r.universe.deduplicated_count,1);assert.equal(r.results[2].source_error.code,'UPSTREAM_HTTP_503');assert.equal(r.batch.storage_writes,false);});
test('batch deadline prevents queued starts and loader receives bounded timeouts',async()=>{let now=NOW,calls=0;const r=await runSwingScreen({symbols:Array.from({length:20},(_,i)=>String(600000+i))},{normalize:symbol,now:()=>now,loadHistory:async(s,opts)=>{calls++;assert.ok(opts.timeout_ms<=6500);now+=8000;return {...history(),symbol:s};}});assert.equal(calls,3);assert.equal(r.results.filter(x=>x.reason_codes.includes('BATCH_DEADLINE_EXCEEDED')).length,17);});
test('original watchlist pagination is exactly20 per read, preserves names, and empty list is not full-market scan',async()=>{const rows=Array.from({length:23},(_,i)=>({symbol:'sh'+(600000+i),name:'Test '+i}));let after;const deps={normalize:symbol,now:()=>NOW,listOriginal:async cursor=>(after=cursor,{items:rows.filter(r=>r.symbol>cursor),total:23,has_more:false}),loadHistory:async s=>({...history(),symbol:s})};const one=await runSwingScreen({universe:'original_watchlist'},deps);assert.equal(one.universe.returned,20);assert.equal(one.universe.next_after,'sh600019');assert.equal(one.universe.storage_source,'original');const two=await runSwingScreen({universe:'original_watchlist',after:one.universe.next_after},deps);assert.equal(after,'sh600019');assert.equal(two.universe.returned,3);assert.equal(two.universe.has_more,false);const empty=await runSwingScreen({universe:'original_watchlist'},{...deps,listOriginal:async()=>({items:[],total:0,has_more:false})});assert.equal(empty.results.length,0);});
function raw(d){return JSON.stringify({code:0,data:{[d.symbol]:{qfqday:d.bars.map(b=>[b.date,b.open,b.close,b.high,b.low,b.volume_shares/100])}}});}
function database(){
 const db=new DatabaseSync(':memory:');
 db.exec(readFileSync(new URL('../portable/manual-observations.sql',import.meta.url),'utf8'));
 const queries=[];
 return {db,queries,DB:{
  batch(){throw Error('NO_WRITES_ALLOWED');},
  prepare(q){queries.push(q);const st=db.prepare(q);return {bind(...args){return {
   all:async()=>({results:st.all(...args)}),first:async()=>st.get(...args)??null,
   run(){throw Error('NO_WRITES_ALLOWED');}
  };}};}
 }};
}
test('dispatcher uses fixed free qfq source only; no storage/bridge/credentials, old11 preserved, route auth enforced',async()=>{const oldFetch=globalThis.fetch,oldNow=Date.now;const calls=[];Date.now=()=>NOW;globalThis.fetch=async(url,opts)=>{calls.push(url);assert.equal(opts.redirect,'manual');assert.equal(url,'https://web.ifzq.gtimg.cn/appstock/app/fqkline/get?param=sh600000,day,,,200,qfq');return new Response(raw(history()));};try{const env={DB:{prepare(){throw Error('NO_DB_OR_SECRET_ACCESS');}}};const d=await callData({name:'get_swing_screen',arguments:{symbols:['600000']}},env,'owner','https://site.test');assert.equal(d.results[0].status,'match');assert.equal(d.service.version,'1.28.0-dev.3');assert.equal(d.service.schema_revision,'2026-10-03.public.2');assert.equal(calls.length,1);assert.equal(tools.length,14);for(const name of ['get_quotes','get_bars','get_intraday','get_macd','get_auction','get_diagnostics','get_archive','get_market_context','get_stock_context','get_auction_snapshot','get_auction_series'])assert.ok(tools.find(t=>t.name===name));assert.ok(tools.every(t=>t.annotations.readOnlyHint));await assert.rejects(()=>callData({name:'get_swing_screen',arguments:{symbols:['600000']}},env),/AUTH_REQUIRED/);for(const path of ['/mcp','/api/market']){const body=path==='/mcp'?{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'get_swing_screen',arguments:{symbols:['600000']}}}:{name:'get_swing_screen',arguments:{symbols:['600000']}};const r=await worker.fetch(new Request('https://site.test'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),env);assert.equal(r.status,401);}assert.equal(calls.length,1);}finally{globalThis.fetch=oldFetch;Date.now=oldNow;}});
test('source wrong adjustment and request errors remain per-symbol insufficiency; errors do not reflect upstream content',async()=>{const oldFetch=globalThis.fetch,oldNow=Date.now;Date.now=()=>NOW;globalThis.fetch=async()=>new Response(JSON.stringify({code:0,data:{sh600000:{day:[]}}}));try{const d=await callData({name:'get_swing_screen',arguments:{symbols:['600000','bad']}},{},'owner');assert.equal(d.summary.insufficient_data,2);assert.equal(d.results[0].reason_codes[0],'SOURCE_UNAVAILABLE');assert.equal(d.results[1].reason_codes[0],'INVALID_SYMBOL');}finally{globalThis.fetch=oldFetch;Date.now=oldNow;}const d=await runSwingScreen({symbols:['600000']},{normalize:symbol,now:()=>NOW,loadHistory:async()=>{throw Error('private secret error content');}});assert.equal(d.results[0].source_error.code,'SOURCE_REQUEST_FAILED');});
