import test from 'node:test';import assert from 'node:assert/strict';import {openLocalDatabase} from '../portable/sqlite.mjs';import {listWatchlist,changeWatchlist,accountWatchlist} from '../portable/local-watchlist.mjs';import worker,{symbol,tools} from '../src/worker.mjs';
const database=()=>openLocalDatabase(':memory:');
const verify=async s=>({symbol:s,name:'核验名称 '+s});
test('durable add duplicate switch reload removal; no seeded holdings',async()=>{const env=database();assert.equal((await listWatchlist(env,'a')).total,0);await changeWatchlist(env,'a','add','sz000001',verify);await changeWatchlist(env,'a','add','sh600000',verify);await changeWatchlist(env,'a','add','sz000001',()=>{throw Error('duplicate must not re-fetch')});assert.equal((await listWatchlist(env,'a')).total,2);await changeWatchlist(env,'a','select','sz000001',verify);assert.equal((await listWatchlist(env,'a')).selected.symbol,'sz000001');await changeWatchlist(env,'a','remove','sz000001',verify);await changeWatchlist(env,'a','remove','sz000001',verify);const d=await listWatchlist(env,'a');assert.equal(d.total,1);assert.equal(d.selected,null);});
test('owners fully separated; selection cannot refer to absent or another user stock',async()=>{const env=database();await changeWatchlist(env,'a','add','sz000001',verify);await changeWatchlist(env,'b','select','sz000001',verify);await changeWatchlist(env,'b','remove','sz000001',verify);assert.equal((await listWatchlist(env,'b')).total,0);assert.equal((await listWatchlist(env,'b')).selected,null);assert.equal((await listWatchlist(env,'a')).total,1);});
test('101+ watchlist is paginated without arbitrary total count limit and selected pin survives',async()=>{const env=database();for(let i=0;i<205;i++)await changeWatchlist(env,'a','add','sh'+String(600000+i),verify);await changeWatchlist(env,'a','select','sh600204',verify);const one=await listWatchlist(env,'a'),two=await listWatchlist(env,'a',one.next_after),three=await listWatchlist(env,'a',two.next_after);assert.deepEqual([one.items.length,two.items.length,three.items.length],[100,100,5]);assert.equal(one.total,205);assert.equal(one.selected.symbol,'sh600204');assert.equal(three.has_more,false);assert.equal(new Set([...one.items,...two.items,...three.items].map(x=>x.symbol)).size,205);});
test('quote lookup failure or mismatch never saves unverified symbol',async()=>{const env=database();for(const q of [{symbol:'sh600000',name:'Wrong'},null,{symbol:'sz000001',name:''},{symbol:'sz000001',name:'x',error:{}}])await assert.rejects(()=>changeWatchlist(env,'a','add','sz000001',async()=>q));assert.equal((await listWatchlist(env,'a')).total,0);});
test('database outage fails closed; retry after uncertain committed add is idempotent',async()=>{await assert.rejects(()=>listWatchlist({},'a'));const env=database();await changeWatchlist(env,'a','add','sz000001',verify);await changeWatchlist(env,'a','add','sz000001',verify);assert.equal((await listWatchlist(env,'a')).total,1);});
test('unauthenticated watchlist rejects before read/write; market MCP tools remain thirteen read-only',async()=>{for(const action of ['list','add','remove','select']){const r=await worker.fetch(new Request('http://127.0.0.1:8765/api/watchlist',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,symbol:'000001'})}));assert.equal(r.status,501);}assert.equal(tools.length,14);assert.ok(tools.every(t=>t.annotations.readOnlyHint));});
// Mocked dispatcher identity below tests route logic only, not production authentication.
test('route validates code alias, invalid stock, request size, extra owner, cross-site and content type',async()=>{const env=database(),deps={symbol,verify};async function call(a,headers={}){return accountWatchlist(new Request('http://127.0.0.1:8765/api/watchlist',{method:'POST',headers:{'content-type':'application/json','oai-authenticated-user-id':'mock-owner',...headers},body:JSON.stringify(a)}),env,'mock-owner',deps);}
for(const code of ['000001','sz000001','000001.SZ'])assert.equal((await call({action:'add',symbol:code})).status,200);assert.equal((await listWatchlist(env,'mock-owner')).total,1);
for(const code of ['上证指数','6009999','sh000001','700001','<script>'])assert.equal((await call({action:'add',symbol:code})).status,400);assert.equal((await call({action:'list',owner:'other'})).status,400);assert.equal((await call({action:'list',after:'x'.repeat(2001)})).status,400);assert.equal((await call({action:'list'},{origin:'https://evil.test'})).status,403);assert.equal((await call({action:'list'},{'content-type':'text/plain'})).status,415);});
