// The provider taxonomy can contain nested industries; returned ranks are not additive market breadth.
export const SECTOR_BASE='https://push2delay.eastmoney.com/api/qt/clist/get?pn=1&pz=10&np=1&fltt=2&invt=2&fid=f3&fs=m%3A90+t%3A2&fields=f2,f3,f4,f12,f13,f14,f104,f105,f106,f124,f297';
export function parseSectors(raw,direction,fetched=Date.now()){
 const root=JSON.parse(raw),d=root.data;if(root.rc!==0||!d||!Array.isArray(d.diff)||!Number.isInteger(d.total)||d.total<d.diff.length||!d.diff.length)throw Error('SECTOR_LIST_UNAVAILABLE');
 const seen=new Set(),sectors=d.diff.map(r=>{if(!/^BK\d{4,6}$/.test(r.f12)||r.f13!==90||typeof r.f14!=='string'||!r.f14.trim()||seen.has(r.f12))throw Error('INVALID_SECTOR_ID');seen.add(r.f12);
 const num=(v,positive=false)=>{if(typeof v!=='number'||!Number.isFinite(v)||(positive&&v<=0))throw Error('INVALID_SECTOR_VALUE');return v;};
 const date=String(r.f297??'');if(!/^\d{8}$/.test(date))throw Error('SECTOR_DATE_UNAVAILABLE');const session=date.replace(/^(\d{4})(\d{2})(\d{2})$/,'$1-$2-$3');if(new Date(session+'T00:00:00Z').toISOString().slice(0,10)!==session||session>new Date(fetched+28800000).toISOString().slice(0,10))throw Error('INVALID_SECTOR_DATE');
 return {code:r.f12,name:r.f14,index_points:num(r.f2,true),change_percent:num(r.f3),change_points:num(r.f4),session_date:null,provider_date_label:session,date_field_semantics:'f297 date-shaped label; effective-session meaning not independently verified',source_timestamp:null,fetched_at:new Date(fetched).toISOString(),freshness:{status:'unknown',reason:'Source supplies a date-shaped f297 field but no verified timestamp or effective session date; delayed feed'},source:'eastmoney',unit:'index points; percent change'};});
 for(let i=1;i<sectors.length;i++)if(direction==='leaders'?sectors[i].change_percent>sectors[i-1].change_percent:sectors[i].change_percent<sectors[i-1].change_percent)throw Error('INVALID_SECTOR_SORT');
 return {direction,sectors,provider_total:d.total,returned:sectors.length,fetched_at:new Date(fetched).toISOString()};
}
export const SINA_SECTORS='https://vip.stock.finance.sina.com.cn/q/view/newSinaHy.php';
export function parseSinaSectors(raw,fetched=Date.now()){
 const match=raw.trim().match(/^var S_Finance_bankuai_sinaindustry\s*=\s*(\{[\s\S]*\});?$/);if(!match)throw Error('INVALID_SINA_SECTOR_WRAPPER');const data=JSON.parse(match[1]);if(!data||Array.isArray(data)||typeof data!=='object'||!Object.keys(data).length)throw Error('SINA_SECTORS_UNAVAILABLE');
 const sectors=Object.entries(data).map(([key,value])=>{if(typeof value!=='string')throw Error('INVALID_SINA_SECTOR');const f=value.split(',');if(f.length!==13||f[0]!==key||!/^new_[a-z0-9]+$/.test(key)||!f[1]||f[5].trim()===''||!Number.isFinite(Number(f[5])))throw Error('INVALID_SINA_SECTOR');return {code:key,name:f[1],change_percent:Number(f[5]),index_points:null,session_date:null,source_timestamp:null,fetched_at:new Date(fetched).toISOString(),freshness:{status:'unknown',reason:'Source provides no date or intraday timestamp; current-session freshness cannot be verified'},source:'sina',unit:'provider sector average percent change; not an index level or Eastmoney taxonomy'};});
 sectors.sort((a,b)=>b.change_percent-a.change_percent);return {sectors,provider_total:sectors.length,fetched_at:new Date(fetched).toISOString()};
}
export async function sectorContext(fetchText,now=Date.now){
 const [results,sina]=await Promise.all([Promise.all(['leaders','laggards'].map(async direction=>{const started=now();try{return {...parseSectors(await fetchText(SECTOR_BASE+'&po='+(direction==='leaders'?1:0)),direction,now()),request_latency_ms:now()-started};}catch(e){return {direction,error:String(e.message).slice(0,180),sectors:[]};}})),(async()=>{const started=now();try{return {...parseSinaSectors(await fetchText(SINA_SECTORS),now()),request_latency_ms:now()-started};}catch(e){return {error:String(e.message).slice(0,180)};}})()]);
 const eastAvailable=results.some(r=>r.sectors.length>0),useSina=!eastAvailable&&!!sina.sectors;
 return {available:eastAvailable||useSina,source:useSina?'sina':'eastmoney',source_endpoint:useSina?'vip.stock.finance.sina.com.cn/q/view/newSinaHy.php':'push2delay.eastmoney.com',selection_reason:useSina?'EASTMONEY_UNAVAILABLE_WHOLE_SINA_CLASSIFICATION_FALLBACK':eastAvailable?'EASTMONEY_PRIMARY_WITH_EXPLICIT_PARTIAL_COVERAGE':'ALL_SECTOR_SOURCES_UNAVAILABLE',feed_delay:useSina?'unknown; no source timestamp':'delayed endpoint; exact delay unknown',taxonomy:useSina?'Sina industry classification; different from Eastmoney, never merged':'Eastmoney mixed-level industry classification, may include nested/overlapping sectors',leaders:useSina?sina.sectors.slice(0,10):results[0].sectors,laggards:useSina?[...sina.sectors].reverse().slice(0,10):results[1].sectors,requests:results.map(({sectors,...meta})=>meta),fallback_candidate:(({sectors,...meta})=>meta)(sina),source_timestamp:null,scope:'Top/bottom 10 within selected provider industry classification; no stock-sector attribution, no full-market breadth or sector history',warnings:['SECTOR_FRESHNESS_UNVERIFIED; retrieval time is not data update time','SECTORS_MAY_OVERLAP; do not add constituent counts or turnover','LEADER_AND_LAGGARD_REQUESTS_MAY_NOT_BE_ATOMIC','PUBLIC_ENDPOINT_SCHEMA_AND_COVERAGE_NOT_EXCHANGE_CERTIFIED',useSina?'SINA_CLASSIFICATION_DIFFERS_FROM_EASTMONEY; do not compare ranks across sources':'DELAYED_SOURCE_NOT_REALTIME']};
}
